from AllProgramm.new_window1 import new_window1_size_text
from AllProgramm.my_calculate import my_calculate_window
from AllProgramm.statusBar import StatusBar
from AllProgramm.new_CanvasWindow import new_window
from AllProgramm.myTime import myTeme
from AllProgramm.my_Cal import mycal
from AllProgramm.new_Pomah import newPomaq
from AllProgramm.Auto_close import windowsOpenWin
from AllProgramm.my_StytsColor import myStytsColor
from AllProgramm.window_manager import setup_window_closing